# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: c23051a253dff140c441a98165309f8e650f501de41e6ec89a8c0ae829228f920d9b01bb3036f40999f82db190ea8b6cea3f0aea8cfe88bf2011a74978035774

test:
  secret_key_base: dc68afdc45f57fbd25e113a17deb611b9ca14ff2a98b53bde6d6dcc6eec8fe1091e30fee41598d1743c8a44f16f1a2621aa3a3b9489a05b0b2b66fd57be9741b

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
